   // countryData.js
   export const countryOptions = [
    { value: 'AF', label: 'Afghanistan', phoneCode: '93' },
    { value: 'AL', label: 'Albania', phoneCode: '355' },
    { value: 'DZ', label: 'Algeria', phoneCode: '213' },
    { value: 'AD', label: 'Andorra', phoneCode: '376' },
    { value: 'AO', label: 'Angola', phoneCode: '244' },
    { value: 'AG', label: 'Antigua and Barbuda', phoneCode: '1' },
    { value: 'AR', label: 'Argentina', phoneCode: '54' },
    { value: 'AM', label: 'Armenia', phoneCode: '374' },
    { value: 'AU', label: 'Australia', phoneCode: '61' },
    { value: 'AT', label: 'Austria', phoneCode: '43' },
    { value: 'AZ', label: 'Azerbaijan', phoneCode: '994' },
    { value: 'BS', label: 'Bahamas', phoneCode: '1' },
    { value: 'BH', label: 'Bahrain', phoneCode: '973' },
    { value: 'BD', label: 'Bangladesh', phoneCode: '880' },
    { value: 'BB', label: 'Barbados', phoneCode: '1' },
    { value: 'BY', label: 'Belarus', phoneCode: '375' },
    { value: 'BE', label: 'Belgium', phoneCode: '32' },
    { value: 'BZ', label: 'Belize', phoneCode: '501' },
    { value: 'BJ', label: 'Benin', phoneCode: '229' },
    { value: 'BT', label: 'Bhutan', phoneCode: '975' },
    { value: 'BO', label: 'Bolivia', phoneCode: '591' },
    { value: 'BA', label: 'Bosnia and Herzegovina', phoneCode: '387' },
    { value: 'BW', label: 'Botswana', phoneCode: '267' },
    { value: 'BR', label: 'Brazil', phoneCode: '55' },
    { value: 'BN', label: 'Brunei', phoneCode: '673' },
    { value: 'BG', label: 'Bulgaria', phoneCode: '359' },
    { value: 'BF', label: 'Burkina Faso', phoneCode: '226' },
    { value: 'BI', label: 'Burundi', phoneCode: '257' },
    { value: 'KH', label: 'Cambodia', phoneCode: '855' },
    { value: 'CM', label: 'Cameroon', phoneCode: '237' },
    { value: 'CA', label: 'Canada', phoneCode: '1' },
    { value: 'CV', label: 'Cape Verde', phoneCode: '238' },
    { value: 'CF', label: 'Central African Republic', phoneCode: '236' },
    { value: 'TD', label: 'Chad', phoneCode: '235' },
    { value: 'CL', label: 'Chile', phoneCode: '56' },
    { value: 'CN', label: 'China', phoneCode: '86' },
    { value: 'CO', label: 'Colombia', phoneCode: '57' },
    { value: 'KM', label: 'Comoros', phoneCode: '269' },
    { value: 'CG', label: 'Congo', phoneCode: '242' },
    { value: 'CD', label: 'Congo, Democratic Republic', phoneCode: '243' },
    { value: 'CR', label: 'Costa Rica', phoneCode: '506' },
    { value: 'HR', label: 'Croatia', phoneCode: '385' },
    { value: 'CU', label: 'Cuba', phoneCode: '53' },
    { value: 'CY', label: 'Cyprus', phoneCode: '357' },
    { value: 'CZ', label: 'Czech Republic', phoneCode: '420' },
    { value: 'DK', label: 'Denmark', phoneCode: '45' },
    { value: 'DJ', label: 'Djibouti', phoneCode: '253' },
    { value: 'DM', label: 'Dominica', phoneCode: '1' },
    { value: 'DO', label: 'Dominican Republic', phoneCode: '1' },
    { value: 'EC', label: 'Ecuador', phoneCode: '593' },
    { value: 'EG', label: 'Egypt', phoneCode: '20' },
    { value: 'SV', label: 'El Salvador', phoneCode: '503' },
    { value: 'GQ', label: 'Equatorial Guinea', phoneCode: '240' },
    { value: 'ER', label: 'Eritrea', phoneCode: '291' },
    { value: 'EE', label: 'Estonia', phoneCode: '372' },
    { value: 'ET', label: 'Ethiopia', phoneCode: '251' },
    { value: 'FJ', label: 'Fiji', phoneCode: '679' },
    { value: 'FI', label: 'Finland', phoneCode: '358' },
    { value: 'FR', label: 'France', phoneCode: '33' },
    { value: 'GA', label: 'Gabon', phoneCode: '241' },
    { value: 'GM', label: 'Gambia', phoneCode: '220' },
    { value: 'GE', label: 'Georgia', phoneCode: '995' },
    { value: 'DE', label: 'Germany', phoneCode: '49' },
    { value: 'GH', label: 'Ghana', phoneCode: '233' },
    { value: 'GR', label: 'Greece', phoneCode: '30' },
    { value: 'GD', label: 'Grenada', phoneCode: '1' },
    { value: 'GT', label: 'Guatemala', phoneCode: '502' },
    { value: 'GN', label: 'Guinea', phoneCode: '224' },
    { value: 'GW', label: 'Guinea-Bissau', phoneCode: '245' },
    { value: 'GY', label: 'Guyana', phoneCode: '592' },
    { value: 'HT', label: 'Haiti', phoneCode: '509' },
    { value: 'HN', label: 'Honduras', phoneCode: '504' },
    { value: 'HU', label: 'Hungary', phoneCode: '36' },
    { value: 'IS', label: 'Iceland', phoneCode: '354' },
    { value: 'IN', label: 'India', phoneCode: '91' },
    { value: 'ID', label: 'Indonesia', phoneCode: '62' },
    { value: 'IR', label: 'Iran', phoneCode: '98' },
    { value: 'IQ', label: 'Iraq', phoneCode: '964' },
    { value: 'IE', label: 'Ireland', phoneCode: '353' },
    { value: 'IL', label: 'Israel', phoneCode: '972' },
    { value: 'IT', label: 'Italy', phoneCode: '39' },
    { value: 'JM', label: 'Jamaica', phoneCode: '1' },
    { value: 'JP', label: 'Japan', phoneCode: '81' },
    { value: 'JO', label: 'Jordan', phoneCode: '962' },
    { value: 'KZ', label: 'Kazakhstan', phoneCode: '7' },
    { value: 'KE', label: 'Kenya', phoneCode: '254' },
    { value: 'KI', label: 'Kiribati', phoneCode: '686' },
    { value: 'KP', label: 'Korea, North', phoneCode: '850' },
    { value: 'KR', label: 'Korea, South', phoneCode: '82' },
    { value: 'KW', label: 'Kuwait', phoneCode: '965' },
    { value: 'KG', label: 'Kyrgyzstan', phoneCode: '996' },
    { value: 'LA', label: 'Laos', phoneCode: '856' },
    { value: 'LV', label: 'Latvia', phoneCode: '371' },
    { value: 'LB', label: 'Lebanon', phoneCode: '961' },
    { value: 'LS', label: 'Lesotho', phoneCode: '266' },
    { value: 'LR', label: 'Liberia', phoneCode: '231' },
    { value: 'LY', label: 'Libya', phoneCode: '218' },
    { value: 'LI', label: 'Liechtenstein', phoneCode: '423' },
    { value: 'LT', label: 'Lithuania', phoneCode: '370' },
    { value: 'LU', label: 'Luxembourg', phoneCode: '352' },
    { value: 'MK', label: 'Macedonia', phoneCode: '389' },
    { value: 'MG', label: 'Madagascar', phoneCode: '261' },
    { value: 'MW', label: 'Malawi', phoneCode: '265' },
    { value: 'MY', label: 'Malaysia', phoneCode: '60' },
    { value: 'MV', label: 'Maldives', phoneCode: '960' },
    { value: 'ML', label: 'Mali', phoneCode: '223' },
    { value: 'MT', label: 'Malta', phoneCode: '356' },
    { value: 'MH', label: 'Marshall Islands', phoneCode: '692' },
    { value: 'MR', label: 'Mauritania', phoneCode: '222' },
    { value: 'MU', label: 'Mauritius', phoneCode: '230' },
    { value: 'MX', label: 'Mexico', phoneCode: '52' },
    { value: 'FM', label: 'Micronesia', phoneCode: '691' },
    { value: 'MD', label: 'Moldova', phoneCode: '373' },
    { value: 'MC', label: 'Monaco', phoneCode: '377' },
    { value: 'MN', label: 'Mongolia', phoneCode: '976' },
    { value: 'ME', label: 'Montenegro', phoneCode: '382' },
    { value: 'MA', label: 'Morocco', phoneCode: '212' },
    { value: 'MZ', label: 'Mozambique', phoneCode: '258' },
    { value: 'MM', label: 'Myanmar', phoneCode: '95' },
    { value: 'NA', label: 'Namibia', phoneCode: '264' },
    { value: 'NR', label: 'Nauru', phoneCode: '674' },
    { value: 'NP', label: 'Nepal', phoneCode: '977' },
    { value: 'NL', label: 'Netherlands', phoneCode: '31' },
    { value: 'NZ', label: 'New Zealand', phoneCode: '64' },
    { value: 'NI', label: 'Nicaragua', phoneCode: '505' },
    { value: 'NE', label: 'Niger', phoneCode: '227' },
    { value: 'NG', label: 'Nigeria', phoneCode: '234' },
    { value: 'NO', label: 'Norway', phoneCode: '47' },
    { value: 'OM', label: 'Oman', phoneCode: '968' },
    { value: 'PK', label: 'Pakistan', phoneCode: '92' },
    { value: 'PW', label: 'Palau', phoneCode: '680' },
    { value: 'PA', label: 'Panama', phoneCode: '507' },
    { value: 'PG', label: 'Papua New Guinea', phoneCode: '675' },
    { value: 'PY', label: 'Paraguay', phoneCode: '595' },
    { value: 'PE', label: 'Peru', phoneCode: '51' },
    { value: 'PH', label: 'Philippines', phoneCode: '63' },
    { value: 'PL', label: 'Poland', phoneCode: '48' },
    { value: 'PT', label: 'Portugal', phoneCode: '351' },
    { value: 'QA', label: 'Qatar', phoneCode: '974' },
    { value: 'RO', label: 'Romania', phoneCode: '40' },
    { value: 'RU', label: 'Russia', phoneCode: '7' },
    { value: 'RW', label: 'Rwanda', phoneCode: '250' },
    { value: 'KN', label: 'Saint Kitts and Nevis', phoneCode: '1' },
    { value: 'LC', label: 'Saint Lucia', phoneCode: '1' },
    { value: 'VC', label: 'Saint Vincent and the Grenadines', phoneCode: '1' },
    { value: 'WS', label: 'Samoa', phoneCode: '685' },
    { value: 'SM', label: 'San Marino', phoneCode: '378' },
    { value: 'ST', label: 'Sao Tome and Principe', phoneCode: '239' },
    { value: 'SA', label: 'Saudi Arabia', phoneCode: '966' },
    { value: 'SN', label: 'Senegal', phoneCode: '221' },
    { value: 'RS', label: 'Serbia', phoneCode: '381' },
    { value: 'SC', label: 'Seychelles', phoneCode: '248' },
    { value: 'SL', label: 'Sierra Leone', phoneCode: '232' },
    { value: 'SG', label: 'Singapore', phoneCode: '65' },
    { value: 'SK', label: 'Slovakia', phoneCode: '421' },
    { value: 'SI', label: 'Slovenia', phoneCode: '386' },
    { value: 'SB', label: 'Solomon Islands', phoneCode: '677' },
    { value: 'SO', label: 'Somalia', phoneCode: '252' },
    { value: 'ZA', label: 'South Africa', phoneCode: '27' },
    { value: 'SS', label: 'South Sudan', phoneCode: '211' },
    { value: 'ES', label: 'Spain', phoneCode: '34' },
    { value: 'LK', label: 'Sri Lanka', phoneCode: '94' },
    { value: 'SD', label: 'Sudan', phoneCode: '249' },
    { value: 'SR', label: 'Suriname', phoneCode: '597' },
    { value: 'SZ', label: 'Swaziland', phoneCode: '268' },
    { value: 'SE', label: 'Sweden', phoneCode: '46' },
    { value: 'CH', label: 'Switzerland', phoneCode: '41' },
    { value: 'SY', label: 'Syria', phoneCode: '963' },
    { value: 'TW', label: 'Taiwan', phoneCode: '886' },
    { value: 'TJ', label: 'Tajikistan', phoneCode: '992' },
    { value: 'TZ', label: 'Tanzania', phoneCode: '255' },
    { value: 'TH', label: 'Thailand', phoneCode: '66' },
    { value: 'TL', label: 'Timor-Leste', phoneCode: '670' },
    { value: 'TG', label: 'Togo', phoneCode: '228' },
    { value: 'TO', label: 'Tonga', phoneCode: '676' },
    { value: 'TT', label: 'Trinidad and Tobago', phoneCode: '1' },
    { value: 'TN', label: 'Tunisia', phoneCode: '216' },
    { value: 'TR', label: 'Turkey', phoneCode: '90' },
    { value: 'TM', label: 'Turkmenistan', phoneCode: '993' },
    { value: 'TV', label: 'Tuvalu', phoneCode: '688' },
    { value: 'UG', label: 'Uganda', phoneCode: '256' },
    { value: 'UA', label: 'Ukraine', phoneCode: '380' },
    { value: 'AE', label: 'United Arab Emirates', phoneCode: '971' },
    { value: 'GB', label: 'United Kingdom', phoneCode: '44' },
    { value: 'US', label: 'United States', phoneCode: '1' },
    { value: 'UY', label: 'Uruguay', phoneCode: '598' },
    { value: 'UZ', label: 'Uzbekistan', phoneCode: '998' },
    { value: 'VU', label: 'Vanuatu', phoneCode: '678' },
    { value: 'VA', label: 'Vatican City', phoneCode: '379' },
    { value: 'VE', label: 'Venezuela', phoneCode: '58' },
    { value: 'VN', label: 'Vietnam', phoneCode: '84' },
    { value: 'YE', label: 'Yemen', phoneCode: '967' },
    { value: 'ZM', label: 'Zambia', phoneCode: '260' },
    { value: 'ZW', label: 'Zimbabwe', phoneCode: '263' }
  ];